---------------------------------------
Begin Slurm Prolog: Mar-03-2025 06:36:51
Job ID:    1494901
User ID:   yzhang3942
Account:   coc
Job name:  evaluateGene
Partition: ice-gpu
QOS:       coe-ice
---------------------------------------
Launching AIsurBL
atl1-1-01-005-15-0.pace.gatech.edu
Lmod has detected the following error: The following module(s) are unknown:
"gcc/13.2.0"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "gcc/13.2.0"

Also make sure that all modulefiles written in TCL start with the string
#%Module




The following have been reloaded with a version change:
  1) cuda/12.6.1 => cuda/12.1.1

/var/lib/slurm/slurmd/job1494901/slurm_script: line 17: /opt/apps/Module/anaconda3/2021.11/bin/activate: No such file or directory
Traceback (most recent call last):
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/./sota/ultralytics/test.py", line 164, in <module>
    main()
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/./sota/ultralytics/test.py", line 130, in main
    model = YOLO(args.network)
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/sota/ultralytics/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/sota/ultralytics/ultralytics/engine/model.py", line 143, in __init__
    self._new(model, task=task, verbose=verbose)
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/sota/ultralytics/ultralytics/engine/model.py", line 251, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/sota/ultralytics/ultralytics/nn/tasks.py", line 319, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "/storage/ice1/0/2/yzhang3942/llm-guided-evolution/sota/ultralytics/ultralytics/nn/tasks.py", line 959, in parse_model
    for i, (f, n, m, args) in enumerate(d["backbone"] + d["head"]):  # from, number, module, args
ValueError: too many values to unpack (expected 4)
---------------------------------------
Begin Slurm Epilog: Mar-03-2025 06:37:16
Job ID:        1494901
User ID:       yzhang3942
Account:       coc
Job name:      evaluateGene
Resources:     cpu=4,gres/gpu:a100=2,mem=128G,node=1
Rsrc Used:     cput=00:01:44,vmem=0,walltime=00:00:26,mem=579372K,energy_used=0
Partition:     ice-gpu
QOS:           coe-ice
Nodes:         atl1-1-01-005-15-0
---------------------------------------
